version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/var/www/html
    environment:
      VIRTUAL_HOST: support.webikon.sk
      LETSENCRYPT_HOST: support.webikon.sk
      LETSENCRYPT_EMAIL: support@webikon.sk
    restart: always
  db:
    image: mariadb:10.1.18
    volumes:
      - ./db:/var/lib/mysql
      # - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ***MYSQL_ROOT_PASSWORD***
      MYSQL_DATABASE: ***MYSQL_DATABASE***
      MYSQL_USER: ***MYSQL_USER***
      MYSQL_PASSWORD: ***MYSQL_PASSWORD***
    restart: always

networks:
  default:
    external:
      name: internal-network
